# Offense count: 10
Metrics/AbcSize:
  Max: 17

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 173

# Offense count: 26
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 14

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 8