
inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - 'app/**/application*.rb'
    - 'app/channels/application_cable/channel.rb'
    - 'vendor/**/*'
    - 'lib/**'
    - 'tmp/**/*'
  TargetRubyVersion: 2.7
  SuggestExtensions: false
