version: "3"
services:
  db:
    image: mysql:5.8
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file:
      - ./environments/db.env
    volumes:
      - db_data:/var/lib/mysql
      - ./containers/db/conf.d:/etc/mysql/conf.d:ro

  elasticsearch:
    build:
      context: docker_image/elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=es_master
      - discovery.type=single-node
      - discovery.seed_hosts=elasticsearch
      - cluster.name=docker-c1luster
      - bootstrap.memory_lock=true
      - "http.host=0.0.0.0"
    ports:
      - 9200:9200
      - 9300:9300

  headPlugin:
    image: 'mobz/elasticsearch-head:7'
    container_name: head
    ports:
      - '9100:9100'

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./environments/app.env
    volumes:
      - bundle_install:/pinejuice/vendor/bundle
      - ./app:/pinejuice/app
      - ./bin:/pinejuice/bin
      - ./config:/pinejuice/config
      - ./config.ru:/pinejuice/config.ru
      - ./db:/pinejuice/db
      - ./.rubocop.yml:/pinejuice/.rubocop.yml
      - ./.rubocop_todo.yml:/pinejuice/.rubocop_todo.yml
      - ./Gemfile:/pinejuice/Gemfile
      - ./Gemfile.lock:/pinejuice/Gemfile.lock
      - ./lib:/pinejuice/lib
      - ./public:/pinejuice/public
      - ./Rakefile:/pinejuice/Rakefile
      - ./spec:/pinejuice/spec
      - ./log:/pinejuice/log
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    ports:
      - "3000:3000"
      - "5000:5000"
    stdin_open: true
    tty: true
    links:
      - db
      - elasticsearch

volumes:
  db_data:
    driver: local
  bundle_install:
